includes = [
    "<stdint.h>",
    "<stddef.h>",
    "<stdlib.h>",
    "<stdbool.h>",
    "<stdarg.h>",
    "<stdio.h>",
    "<string.h>",
]

files = [ 
    "rjd_platform.h",
    "rjd_debug.h",
    "rjd_alloc.h",
    "rjd_rng.h",
    "rjd_array.h",
    "rjd_profiler.h",
    "rjd_cmd.h"
]

concat = "#pragma once\n\n"

concat += "////////////////////////////////////////////////////////////////////////////////\n"
concat += "// autogenerated rjd.h\n"
concat += "////////////////////////////////////////////////////////////////////////////////\n\n"
concat += "#if RJD_IMPL\n"

for include in includes:
    concat += "\t#include " + include + "\n"

concat += "#endif // RJD_IMPL\n\n"
    

for filename in files:
    with open(filename, "r") as file:
        data = file.read()
        concat += "////////////////////////////////////////////////////////////////////////////////\n"
        concat += "// " + filename + "\n"
        concat += "////////////////////////////////////////////////////////////////////////////////\n"
        concat += "\n"
        concat += data;
        concat += "\n"

with open("rjd.h", "w") as file:
    file.write(concat)
