name: CI

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master, ci-test ]

jobs:
  build_osx:
    name: OSX Build & Test
    runs-on: macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: make check
        run: make check
